server:
  port: 9002


app:
  security:
    jwt:
      keystore-location: keystore.jks
      keystore-password: password
      key-alias: jwtsigning
      private-key-passphrase: password


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_registration
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
